In [86]:
import tensorflow as tf
x_train = [[1., 2.], [2., 3.], [3., 1.], [4., 3.], [5., 3.], [6., 2.]]
y_train = [[0.], [0.], [0.], [1.], [1.], [1.]]
x_test = [[5., 2.]]
y_test = [1.]

In [87]:
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(len(x_train))

In [88]:
for e in dataset:
    print(e)

(<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[1., 2.],
       [2., 3.],
       [3., 1.],
       [4., 3.],
       [5., 3.],
       [6., 2.]], dtype=float32)>, <tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)>)


In [109]:
W = tf.Variable([[2.],[1.]])#, name = 'weight')
b = tf.Variable([0.,0.])#, name = 'bias')

In [110]:
def logistic_regression (features) : 
    hypothesis = tf.sigmoid(tf.matmul(features, W) + b)
    return hypothesis

In [111]:
def loss_fn (hypothesis, labels):
    cost = -tf.reduce_mean(labels * tf.math.log(hypothesis) + (1-labels) * tf.math.log(1- hypothesis))
    return cost

In [112]:
def grad(hypothesis, features, labels):
    with tf.GradientTape() as tape:
        loss_value = loss_fn(hypothesis, labels)
    return tape.gradient(loss_value, [W,b])

In [113]:
optimizer = tf.optimizers.SGD(learning_rate = 0.01)
EPOCHS = 100
for step in range(EPOCHS):
    for features, labels in iter(dataset):
        print('feature is', features)
        hypothesis = logistic_regression(features)
        grads = grad(hypothesis, features, labels)
        optimizer.apply_gradients(grads_and_vars = zip(grads, [W,b]))
        if step % 100 == 0:
            print('Iter: {}, Loss : {:.4f}'.format(step, loss_fn(features, labels)))

feature is tf.Tensor(
[[1. 2.]
 [2. 3.]
 [3. 1.]
 [4. 3.]
 [5. 3.]
 [6. 2.]], shape=(6, 2), dtype=float32)


ValueError: No gradients provided for any variable: ['Variable:0', 'Variable:0'].